### PR TITLE
Add experimental filtering sampler

### LINKED ISSUE #16: Thinking about dropping the field resolving events from the trace
Currently we're tracing the field resolving event, although it's good to have more granularity in the trace, but i can see few disadvantage of this approach:  

* Making the trace hard to read if there are too many events. In some trace that we actually have in production, the amount of field resolving traces are thousands , and it's almost impossible to read it properly. It does not provide much value to us in that case.  
* If error happens for some request, usually it does not happen at the field resolving phase, but somewhere else, like calling external system ( for example DB). So it make senses to have less events in the trace, and focus on what important. 

So what i'm proposing is we remove the `[:absinthe, :resolve, :field, :start]` and `[:absinthe, :resolve, :field, :stop]` from the library. Then we can have less events per trace and also still able to gain visibility of the GraphQL request.

### PR DESCRIPTION
**Pull request by maciej-szlosarczyk**
Signed-off-by: Maciej Szlosarczyk <maciej@mindvalley.com>

This would be one way to fix #16.

### CODE REVIEW

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **maciej-szlosarczyk** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fmv-opentelemetry).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/mv-opentelemetry/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by maciej-szlosarczyk** [comment]
For graphql events it would be activated like this:

```ex
  config :opentelemetry,
    sampler:
      {MvOpentelemetry.FilteringSampler,
        %{
          filter_list: [~r/graphql.resolve.field[a-z_\.]+/],
          default: {:parent_based, %{root: {:trace_id_ratio_based, 0.01}}}
        }}

**Review by antonsatin — APPROVED** [review]
LGTM

**Comment by sauron-droid** [comment]
LGTM label has been added.  <details>Git tree hash: 015401c1aaa0d19703ad01b86cf7a9b18307809e</details>

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/mv-opentelemetry/pull/21#pullrequestreview-856421841" title="Approved">antonsatin</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fmv-opentelemetry).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/mindvalley/mv-opentelemetry/blob/main/OWNERS)~~ [antonsatin]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by maciej-szlosarczyk** [comment]
Superseded by #25

**Pull request closed without merging**
