### PR TITLE
Update underlying otel dependencies

### PR DESCRIPTION
**Pull request by antonsatin**
This updates telemetry and opentelemetry to 1.x versions

Thanks @maciej-szlosarczyk for help

### CODE REVIEW

**Comment by sauron-droid** [comment]
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/mindvalley/mv-opentelemetry/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [9a78b92](https://github.com/mindvalley/mv-opentelemetry/commits/9a78b92e7761e3cb62661b47ed6e95b60695ee84) Update underlying otel dependencies

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **antonsatin** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fmv-opentelemetry).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/mindvalley/mv-opentelemetry/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by zacaaron** [comment]
@antonsatin please refer to this line for the fix on Google download server expired key prob: https://github.com/mindvalley/mv-spaces-elixir-engine/blob/main/jenkins/jenkinsfile-ci#L25

Add that before doing a `sudo apt-get update`

**Comment by antonsatin** [comment]
@zacaaron yep added, would you mind to review?

**Review by zacaaron — APPROVED** [review]
Jenkins is green so LGTM

**Comment by sauron-droid** [comment]
LGTM label has been added.  <details>Git tree hash: 45714949c231e976ad4ef94167a9c394aeef4b7e</details>

**Comment by sauron-droid** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mindvalley/mv-opentelemetry/pull/36#pullrequestreview-1050596484" title="Approved">zacaaron</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=mindvalley%2Fmv-opentelemetry).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/mindvalley/mv-opentelemetry/blob/main/OWNERS)~~ [zacaaron]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
